name: Compilar APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Buscar y dar permisos a gradlew
      run: |
        GRADLEW_PATH=$(find . -name gradlew -type f)
        echo "GRADLEW_PATH=$GRADLEW_PATH" >> $GITHUB_ENV
        chmod +x "$GRADLEW_PATH"

    - name: Compilar APK Debug
      run: |
        DIR_PATH=$(dirname "$GRADLEW_PATH")
        cd "$DIR_PATH"
        ./gradlew assembleDebug

    - name: Subir APK como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: "**/app/build/outputs/apk/debug/app-debug.apk"
